"""Initial schema.

Hand-written rather than autogenerated. Autogenerate cannot express, and actively
mis-renders, most of what this schema depends on: ``ltree`` columns and their GiST indexes,
range-partitioned telemetry tables, a generated ``tsvector`` column, partial and expression
indexes, the enum types, and the triggers that keep the denormalized ACL columns honest.
Reviewing DDL is also the point — this file is the artifact an auditor reads.

Statements are grouped and applied in order. Each is executed separately because asyncpg
rejects multiple commands in one prepared statement.

Revision ID: 0001_initial
Revises:
Created: 2026-07-28
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ── Extensions ──────────────────────────────────────────────────────────────
# `vector` is created unconditionally even when Qdrant is the backend: the empty
# `chunk_embeddings` table costs nothing, and switching backends should not require a
# migration in the middle of an incident.

EXTENSIONS: tuple[str, ...] = (
    "CREATE EXTENSION IF NOT EXISTS ltree",
    "CREATE EXTENSION IF NOT EXISTS citext",
    "CREATE EXTENSION IF NOT EXISTS pg_trgm",
    "CREATE EXTENSION IF NOT EXISTS vector",
)

# ── Enum types ──────────────────────────────────────────────────────────────
# Created here rather than by the ORM: `create_type=False` on every mapped enum means two
# API replicas booting concurrently cannot race each other emitting CREATE TYPE.

ENUMS: tuple[str, ...] = (
    "CREATE TYPE user_role AS ENUM ('admin','manager','internal_employee','customer','guest')",
    "CREATE TYPE visibility AS ENUM ('public','customer','internal','confidential','restricted')",
    "CREATE TYPE assistant_mode AS ENUM ('internal','customer')",
    "CREATE TYPE chunk_type AS ENUM "
    "('text','heading','table','code','list','caption','form','ocr')",
    "CREATE TYPE ingest_status AS ENUM ('pending','scanning','parsing','chunking','embedding',"
    "'indexing','indexed','failed','quarantined','superseded')",
    "CREATE TYPE job_status AS ENUM ('queued','running','succeeded','failed','dead')",
    "CREATE TYPE message_role AS ENUM ('user','assistant','system')",
    "CREATE TYPE answer_status AS ENUM ('ok','no_answer','refused','clarify','escalated','error')",
    "CREATE TYPE principal_type AS ENUM ('role','user','department')",
    "CREATE TYPE ticket_priority AS ENUM ('low','normal','high','urgent')",
    "CREATE TYPE ticket_status AS ENUM "
    "('open','in_progress','waiting_customer','resolved','closed')",
    "CREATE TYPE feedback_rating AS ENUM ('up','down')",
    "CREATE TYPE eval_metric AS ENUM ('faithfulness','answer_relevancy','context_precision',"
    "'context_recall','citation_correctness','answer_correctness')",
)

# ── Identity ────────────────────────────────────────────────────────────────

IDENTITY: tuple[str, ...] = (
    """
    CREATE TABLE departments (
        id          uuid        NOT NULL,
        name        text        NOT NULL,
        slug        citext      NOT NULL,
        parent_id   uuid        NULL,
        path        ltree       NOT NULL,
        created_at  timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT pk_departments PRIMARY KEY (id),
        CONSTRAINT uq_departments_slug UNIQUE (slug),
        CONSTRAINT fk_departments_parent_id FOREIGN KEY (parent_id)
            REFERENCES departments (id) ON DELETE SET NULL
    )
    """,
    # GiST is what makes `path <@ 'company.engineering'` an index scan; every retrieval
    # request for a manager or above evaluates that operator.
    "CREATE INDEX ix_departments_path ON departments USING gist (path)",
    """
    CREATE TABLE users (
        id                    uuid        NOT NULL,
        email                 citext      NOT NULL,
        password_hash         text        NULL,
        full_name             text        NOT NULL,
        role                  user_role   NOT NULL,
        department_id         uuid        NULL,
        is_active             boolean     NOT NULL DEFAULT true,
        must_change_password  boolean     NOT NULL DEFAULT false,
        mfa_secret            text        NULL,
        recovery_code_hashes  text[]      NOT NULL DEFAULT '{}'::text[],
        external_idp_sub      text        NULL,
        permission_epoch      integer     NOT NULL DEFAULT 1,
        failed_logins         smallint    NOT NULL DEFAULT 0,
        locked_until          timestamptz NULL,
        last_login_at         timestamptz NULL,
        created_at            timestamptz NOT NULL DEFAULT now(),
        updated_at            timestamptz NOT NULL DEFAULT now(),
        deleted_at            timestamptz NULL,
        CONSTRAINT pk_users PRIMARY KEY (id),
        CONSTRAINT uq_users_email UNIQUE (email),
        CONSTRAINT uq_users_external_idp_sub UNIQUE (external_idp_sub),
        CONSTRAINT fk_users_department_id FOREIGN KEY (department_id)
            REFERENCES departments (id) ON DELETE SET NULL
    )
    """,
    "CREATE INDEX ix_users_role_active ON users (role) "
    "WHERE deleted_at IS NULL AND is_active",
    "CREATE INDEX ix_users_department ON users (department_id) WHERE deleted_at IS NULL",
    """
    CREATE TABLE permissions (
        code        text NOT NULL,
        description text NOT NULL,
        category    text NOT NULL,
        CONSTRAINT pk_permissions PRIMARY KEY (code)
    )
    """,
    """
    CREATE TABLE role_permissions (
        role            user_role NOT NULL,
        permission_code text      NOT NULL,
        CONSTRAINT pk_role_permissions PRIMARY KEY (role, permission_code),
        CONSTRAINT fk_role_permissions_permission_code FOREIGN KEY (permission_code)
            REFERENCES permissions (code) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE user_permission_overrides (
        user_id         uuid        NOT NULL,
        permission_code text        NOT NULL,
        effect          varchar(5)  NOT NULL,
        granted_by      uuid        NULL,
        expires_at      timestamptz NULL,
        created_at      timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT pk_user_permission_overrides PRIMARY KEY (user_id, permission_code),
        CONSTRAINT ck_user_permission_overrides_effect_valid
            CHECK (effect IN ('allow','deny')),
        CONSTRAINT fk_user_permission_overrides_user_id FOREIGN KEY (user_id)
            REFERENCES users (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_permission_overrides_permission_code FOREIGN KEY (permission_code)
            REFERENCES permissions (code) ON DELETE CASCADE,
        CONSTRAINT fk_user_permission_overrides_granted_by FOREIGN KEY (granted_by)
            REFERENCES users (id) ON DELETE SET NULL
    )
    """,
    """
    CREATE TABLE refresh_tokens (
        id          uuid        NOT NULL,
        user_id     uuid        NOT NULL,
        jti         uuid        NOT NULL,
        token_hash  bytea       NOT NULL,
        family_id   uuid        NOT NULL,
        expires_at  timestamptz NOT NULL,
        revoked_at  timestamptz NULL,
        user_agent  text        NULL,
        ip          inet        NULL,
        created_at  timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
        CONSTRAINT uq_refresh_tokens_jti UNIQUE (jti),
        CONSTRAINT fk_refresh_tokens_user_id FOREIGN KEY (user_id)
            REFERENCES users (id) ON DELETE CASCADE
    )
    """,
    # Unique on the digest: presenting a token is a lookup by hash, and uniqueness makes
    # the reuse-detection path a single indexed read.
    "CREATE UNIQUE INDEX ix_refresh_token_hash ON refresh_tokens (token_hash)",
    "CREATE INDEX ix_refresh_active ON refresh_tokens (user_id) WHERE revoked_at IS NULL",
    "CREATE INDEX ix_refresh_family ON refresh_tokens (family_id)",
    """
    CREATE TABLE api_keys (
        id           uuid        NOT NULL,
        name         text        NOT NULL,
        prefix       varchar(8)  NOT NULL,
        key_hash     bytea       NOT NULL,
        role         user_role   NOT NULL,
        scopes       text[]      NOT NULL DEFAULT '{}'::text[],
        created_by   uuid        NULL,
        last_used_at timestamptz NULL,
        expires_at   timestamptz NULL,
        revoked_at   timestamptz NULL,
        created_at   timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT pk_api_keys PRIMARY KEY (id),
        CONSTRAINT uq_api_keys_prefix UNIQUE (prefix),
        CONSTRAINT fk_api_keys_created_by FOREIGN KEY (created_by)
            REFERENCES users (id) ON DELETE SET NULL
    )
    """,
    "CREATE UNIQUE INDEX ix_api_keys_key_hash ON api_keys (key_hash)",
)

# ── Collections, documents, chunks ──────────────────────────────────────────

DOCUMENTS: tuple[str, ...] = (
    """
    CREATE TABLE collections (
        id                 uuid        NOT NULL,
        name               text        NOT NULL,
        slug               citext      NOT NULL,
        description        text        NULL,
        mode               assistant_mode NOT NULL,
        default_visibility visibility  NOT NULL DEFAULT 'internal',
        embedding_provider text        NOT NULL,
        embedding_model    text        NOT NULL,
        embedding_dim      integer     NOT NULL,
        vector_backend     text        NOT NULL DEFAULT 'qdrant',
        vector_namespace   text        NOT NULL,
        chunk_strategy     text        NOT NULL DEFAULT 'adaptive',
        chunk_size         integer     NOT NULL DEFAULT 800,
        chunk_overlap      integer     NOT NULL DEFAULT 120,
        is_active          boolean     NOT NULL DEFAULT true,
        created_at         timestamptz NOT NULL DEFAULT now(),
        updated_at         timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT pk_collections PRIMARY KEY (id),
        CONSTRAINT uq_collections_slug UNIQUE (slug),
        CONSTRAINT ck_collections_dim_positive CHECK (embedding_dim > 0),
        CONSTRAINT ck_collections_overlap_sane CHECK (chunk_overlap < chunk_size)
    )
    """,
    """
    CREATE TABLE tags (
        id    uuid   NOT NULL,
        name  citext NOT NULL,
        color text   NULL,
        CONSTRAINT pk_tags PRIMARY KEY (id),
        CONSTRAINT uq_tags_name UNIQUE (name)
    )
    """,
    """
    CREATE TABLE documents (
        id                uuid        NOT NULL,
        collection_id     uuid        NOT NULL,
        title             text        NOT NULL,
        description       text        NULL,
        source_type       text        NOT NULL DEFAULT 'upload',
        source_ref        text        NULL,
        visibility        visibility  NOT NULL,
        visibility_level  smallint    NOT NULL,
        department_id     uuid        NULL,
        department_path   ltree       NULL,
        language          text        NULL,
        owner_id          uuid        NULL,
        active_version_id uuid        NULL,
        effective_from    date        NULL,
        expires_at        date        NULL,
        is_archived       boolean     NOT NULL DEFAULT false,
        created_at        timestamptz NOT NULL DEFAULT now(),
        updated_at        timestamptz NOT NULL DEFAULT now(),
        deleted_at        timestamptz NULL,
        CONSTRAINT pk_documents PRIMARY KEY (id),
        -- Confidential content is meaningless without a department to scope it to; a row
        -- that violated this would be readable by every manager in the company.
        CONSTRAINT ck_documents_confidential_needs_department
            CHECK (visibility <> 'confidential' OR department_path IS NOT NULL),
        CONSTRAINT fk_documents_collection_id FOREIGN KEY (collection_id)
            REFERENCES collections (id) ON DELETE RESTRICT,
        CONSTRAINT fk_documents_department_id FOREIGN KEY (department_id)
            REFERENCES departments (id) ON DELETE SET NULL,
        CONSTRAINT fk_documents_owner_id FOREIGN KEY (owner_id)
            REFERENCES users (id) ON DELETE SET NULL
    )
    """,
    "CREATE INDEX ix_documents_retrievable ON documents (collection_id, visibility_level) "
    "WHERE deleted_at IS NULL AND NOT is_archived AND active_version_id IS NOT NULL",
    "CREATE INDEX ix_documents_dept ON documents USING gist (department_path)",
    # Trigram index so the admin list's `title ILIKE '%…%'` stays indexed; a plain b-tree
    # cannot serve a leading wildcard.
    "CREATE INDEX ix_documents_title_trgm ON documents USING gin (title gin_trgm_ops)",
    "CREATE INDEX ix_documents_owner ON documents (owner_id)",
    """
    CREATE TABLE document_versions (
        id                uuid        NOT NULL,
        document_id       uuid        NOT NULL,
        version_no        integer     NOT NULL,
        storage_uri       text        NOT NULL,
        original_filename text        NOT NULL,
        mime_type         text        NOT NULL,
        size_bytes        bigint      NOT NULL,
        checksum_sha256   bytea       NOT NULL,
        page_count        integer     NULL,
        extracted_chars   integer     NULL,
        used_ocr          boolean     NOT NULL DEFAULT false,
        parser            text        NULL,
        chunk_strategy    text        NULL,
        embedding_model   text        NULL,
        chunk_count       integer     NOT NULL DEFAULT 0,
        token_count       integer     NOT NULL DEFAULT 0,
        status            ingest_status NOT NULL DEFAULT 'pending',
        error_message     text        NULL,
        injection_flags   integer     NOT NULL DEFAULT 0,
        change_note       text        NULL,
        created_by        uuid        NULL,
        created_at        timestamptz NOT NULL DEFAULT now(),
        indexed_at        timestamptz NULL,
        superseded_at     timestamptz NULL,
        CONSTRAINT pk_document_versions PRIMARY KEY (id),
        CONSTRAINT uq_document_versions_document_id_version_no
            UNIQUE (document_id, version_no),
        -- Re-uploading identical bytes is a no-op, not a new version.
        CONSTRAINT uq_document_versions_document_id_checksum_sha256
            UNIQUE (document_id, checksum_sha256),
        CONSTRAINT ck_document_versions_size_positive CHECK (size_bytes > 0),
        CONSTRAINT fk_document_versions_document_id FOREIGN KEY (document_id)
            REFERENCES documents (id) ON DELETE CASCADE,
        CONSTRAINT fk_document_versions_created_by FOREIGN KEY (created_by)
            REFERENCES users (id) ON DELETE SET NULL
    )
    """,
    "CREATE INDEX ix_versions_status ON document_versions (status)",
    "CREATE INDEX ix_versions_document ON document_versions (document_id)",
    # Added after the table exists (mutual reference). NOT VALID is unnecessary here since
    # both tables are empty. ON DELETE SET NULL rather than RESTRICT so purging a failed
    # version cannot wedge the document row.
    """
    ALTER TABLE documents
        ADD CONSTRAINT fk_documents_active_version_id FOREIGN KEY (active_version_id)
        REFERENCES document_versions (id) ON DELETE SET NULL
    """,
    """
    CREATE TABLE document_tags (
        document_id uuid NOT NULL,
        tag_id      uuid NOT NULL,
        CONSTRAINT pk_document_tags PRIMARY KEY (document_id, tag_id),
        CONSTRAINT fk_document_tags_document_id FOREIGN KEY (document_id)
            REFERENCES documents (id) ON DELETE CASCADE,
        CONSTRAINT fk_document_tags_tag_id FOREIGN KEY (tag_id)
            REFERENCES tags (id) ON DELETE CASCADE
    )
    """,
    "CREATE INDEX ix_document_tags_tag_id ON document_tags (tag_id)",
    """
    CREATE TABLE document_acl (
        id              uuid           NOT NULL,
        document_id     uuid           NOT NULL,
        principal_type  principal_type NOT NULL,
        principal_role  user_role      NULL,
        principal_id    uuid           NULL,
        include_subtree boolean        NOT NULL DEFAULT true,
        granted_by      uuid           NULL,
        expires_at      timestamptz    NULL,
        created_at      timestamptz    NOT NULL DEFAULT now(),
        CONSTRAINT pk_document_acl PRIMARY KEY (id),
        -- Exactly one principal shape per row: a grant that is half role and half user is
        -- ambiguous, and ambiguity in an ACL resolves in whichever direction the reader
        -- guesses.
        CONSTRAINT ck_document_acl_principal_shape CHECK (
            (principal_type = 'role'
                AND principal_role IS NOT NULL AND principal_id IS NULL)
            OR (principal_type <> 'role'
                AND principal_id IS NOT NULL AND principal_role IS NULL)
        ),
        CONSTRAINT fk_document_acl_document_id FOREIGN KEY (document_id)
            REFERENCES documents (id) ON DELETE CASCADE,
        CONSTRAINT fk_document_acl_granted_by FOREIGN KEY (granted_by)
            REFERENCES users (id) ON DELETE SET NULL
    )
    """,
    "CREATE INDEX ix_acl_document ON document_acl (document_id)",
    "CREATE INDEX ix_acl_user ON document_acl (principal_id) WHERE principal_type = 'user'",
    """
    CREATE TABLE chunks (
        id               uuid        NOT NULL,
        document_id      uuid        NOT NULL,
        version_id       uuid        NOT NULL,
        collection_id    uuid        NOT NULL,
        ordinal          integer     NOT NULL,
        content          text        NOT NULL,
        content_hash     bytea       NOT NULL,
        token_count      integer     NOT NULL,
        chunk_type       chunk_type  NOT NULL DEFAULT 'text',
        page_from        integer     NULL,
        page_to          integer     NULL,
        heading_path     text[]      NOT NULL DEFAULT '{}'::text[],
        section          text        NULL,
        char_start       integer     NULL,
        char_end         integer     NULL,
        bbox             jsonb       NULL,
        context_header   text        NULL,
        summary          text        NULL,
        keywords         text[]      NOT NULL DEFAULT '{}'::text[],
        language         text        NULL,
        visibility_level smallint    NOT NULL,
        department_path  ltree       NULL,
        vector_point_id  uuid        NULL,
        embedding_model  text        NULL,
        indexed_at       timestamptz NULL,
        injection_flag   boolean     NOT NULL DEFAULT false,
        metadata         jsonb       NOT NULL DEFAULT '{}'::jsonb,
        created_at       timestamptz NOT NULL DEFAULT now(),
        tsv              tsvector    GENERATED ALWAYS AS
                            (to_tsvector('english', coalesce(content, ''))) STORED,
        CONSTRAINT pk_chunks PRIMARY KEY (id),
        CONSTRAINT uq_chunks_version_id_ordinal UNIQUE (version_id, ordinal),
        CONSTRAINT ck_chunks_tokens_positive CHECK (token_count > 0),
        CONSTRAINT fk_chunks_document_id FOREIGN KEY (document_id)
            REFERENCES documents (id) ON DELETE CASCADE,
        CONSTRAINT fk_chunks_version_id FOREIGN KEY (version_id)
            REFERENCES document_versions (id) ON DELETE CASCADE,
        CONSTRAINT fk_chunks_collection_id FOREIGN KEY (collection_id)
            REFERENCES collections (id) ON DELETE RESTRICT
    )
    """,
    "CREATE INDEX ix_chunks_tsv ON chunks USING gin (tsv)",
    "CREATE INDEX ix_chunks_version ON chunks (version_id)",
    "CREATE INDEX ix_chunks_doc ON chunks (document_id)",
    "CREATE INDEX ix_chunks_hash ON chunks (content_hash)",
    "CREATE INDEX ix_chunks_unindexed ON chunks (collection_id) WHERE indexed_at IS NULL",
    "CREATE INDEX ix_chunks_keywords ON chunks USING gin (keywords)",
    # Serves the post-retrieval ACL re-check (enforcement layer 2), which runs on every
    # answered query with a handful of chunk ids.
    "CREATE INDEX ix_chunks_acl ON chunks (collection_id, visibility_level)",
    "CREATE INDEX ix_chunks_dept ON chunks USING gist (department_path)",
    """
    CREATE TABLE ingest_jobs (
        id              uuid          NOT NULL,
        version_id      uuid          NOT NULL,
        job_type        text          NOT NULL,
        status          job_status    NOT NULL DEFAULT 'queued',
        stage           ingest_status NULL,
        attempts        smallint      NOT NULL DEFAULT 0,
        max_attempts    smallint      NOT NULL DEFAULT 3,
        idempotency_key text          NULL,
        error_message   text          NULL,
        error_class     text          NULL,
        payload         jsonb         NOT NULL DEFAULT '{}'::jsonb,
        metrics         jsonb         NOT NULL DEFAULT '{}'::jsonb,
        queued_at       timestamptz   NOT NULL DEFAULT now(),
        started_at      timestamptz   NULL,
        finished_at     timestamptz   NULL,
        worker_id       text          NULL,
        CONSTRAINT pk_ingest_jobs PRIMARY KEY (id),
        CONSTRAINT uq_ingest_jobs_idempotency_key UNIQUE (idempotency_key),
        CONSTRAINT fk_ingest_jobs_version_id FOREIGN KEY (version_id)
            REFERENCES document_versions (id) ON DELETE CASCADE
    )
    """,
    "CREATE INDEX ix_jobs_status ON ingest_jobs (status, queued_at)",
    "CREATE INDEX ix_jobs_version ON ingest_jobs (version_id)",
    """
    CREATE TABLE index_discrepancies (
        id            uuid        NOT NULL,
        collection_id uuid        NOT NULL,
        chunk_id      uuid        NULL,
        kind          text        NOT NULL,
        details       jsonb       NOT NULL DEFAULT '{}'::jsonb,
        detected_at   timestamptz NOT NULL DEFAULT now(),
        repaired_at   timestamptz NULL,
        CONSTRAINT pk_index_discrepancies PRIMARY KEY (id),
        CONSTRAINT fk_index_discrepancies_collection_id FOREIGN KEY (collection_id)
            REFERENCES collections (id) ON DELETE CASCADE
    )
    """,
    "CREATE INDEX ix_discrepancies_open ON index_discrepancies (detected_at) "
    "WHERE repaired_at IS NULL",
    # No embedding table here on purpose. Under the pgvector backend, embeddings live in a
    # per-namespace `emb_<namespace>` table created by `PgVectorStore.ensure_collection`,
    # because a pgvector index requires a fixed dimension and each collection may use a
    # different model. A single shared table would have to guess one dimension for the whole
    # deployment, and guessing wrong is a failed insert on every chunk. The `vector` extension
    # is still created above so that switching backends never needs a migration.
)

# ── Conversations, tickets, outbox ──────────────────────────────────────────

CONVERSATIONS: tuple[str, ...] = (
    """
    CREATE TABLE conversations (
        id                     uuid        NOT NULL,
        user_id                uuid        NULL,
        guest_session_id       text        NULL,
        mode                   assistant_mode NOT NULL,
        collection_ids         uuid[]      NOT NULL DEFAULT '{}'::uuid[],
        title                  text        NULL,
        summary                text        NULL,
        summary_upto_message_id uuid       NULL,
        message_count          integer     NOT NULL DEFAULT 0,
        total_tokens           integer     NOT NULL DEFAULT 0,
        is_pinned              boolean     NOT NULL DEFAULT false,
        is_archived            boolean     NOT NULL DEFAULT false,
        created_at             timestamptz NOT NULL DEFAULT now(),
        last_message_at        timestamptz NULL,
        deleted_at             timestamptz NULL,
        CONSTRAINT pk_conversations PRIMARY KEY (id),
        -- Either an account or a guest session, never neither: an orphan conversation has
        -- no owner to scope its history to.
        CONSTRAINT ck_conversations_has_principal
            CHECK (user_id IS NOT NULL OR guest_session_id IS NOT NULL),
        CONSTRAINT fk_conversations_user_id FOREIGN KEY (user_id)
            REFERENCES users (id) ON DELETE SET NULL
    )
    """,
    "CREATE INDEX ix_conv_user ON conversations (user_id, last_message_at DESC) "
    "WHERE deleted_at IS NULL",
    "CREATE INDEX ix_conv_guest ON conversations (guest_session_id) "
    "WHERE guest_session_id IS NOT NULL",
    """
    CREATE TABLE messages (
        id                uuid        NOT NULL,
        conversation_id   uuid        NOT NULL,
        parent_id         uuid        NULL,
        role              message_role NOT NULL,
        content           text        NOT NULL,
        status            answer_status NULL,
        refusal_reason    text        NULL,
        model             text        NULL,
        provider          text        NULL,
        prompt_tokens     integer     NULL,
        completion_tokens integer     NULL,
        cost_usd          numeric(12,6) NULL,
        latency_ms        integer     NULL,
        ttft_ms           integer     NULL,
        confidence        double precision NULL,
        is_grounded       boolean     NULL,
        finish_reason     text        NULL,
        created_at        timestamptz NOT NULL DEFAULT now(),
        edited_at         timestamptz NULL,
        CONSTRAINT pk_messages PRIMARY KEY (id),
        CONSTRAINT fk_messages_conversation_id FOREIGN KEY (conversation_id)
            REFERENCES conversations (id) ON DELETE CASCADE,
        CONSTRAINT fk_messages_parent_id FOREIGN KEY (parent_id)
            REFERENCES messages (id) ON DELETE SET NULL
    )
    """,
    "CREATE INDEX ix_messages_conv ON messages (conversation_id, created_at)",
    """
    CREATE TABLE message_citations (
        id           uuid     NOT NULL,
        message_id   uuid     NOT NULL,
        chunk_id     uuid     NOT NULL,
        document_id  uuid     NOT NULL,
        version_id   uuid     NOT NULL,
        marker       smallint NOT NULL,
        rank         smallint NOT NULL,
        quote        text     NULL,
        quote_start  integer  NULL,
        quote_end    integer  NULL,
        page         integer  NULL,
        score_dense  double precision NULL,
        score_sparse double precision NULL,
        score_fused  double precision NULL,
        score_rerank double precision NULL,
        was_used     boolean  NOT NULL DEFAULT true,
        CONSTRAINT pk_message_citations PRIMARY KEY (id),
        CONSTRAINT uq_message_citations_message_id_marker UNIQUE (message_id, marker),
        CONSTRAINT fk_message_citations_message_id FOREIGN KEY (message_id)
            REFERENCES messages (id) ON DELETE CASCADE,
        -- RESTRICT, deliberately: it must be impossible to delete content that a stored
        -- answer cites. A cascade here would quietly rewrite audit history, which is the
        -- one thing a citation exists to protect. Deletion goes through the purge path,
        -- which archives citing messages first.
        CONSTRAINT fk_message_citations_chunk_id FOREIGN KEY (chunk_id)
            REFERENCES chunks (id) ON DELETE RESTRICT,
        CONSTRAINT fk_message_citations_document_id FOREIGN KEY (document_id)
            REFERENCES documents (id) ON DELETE RESTRICT,
        CONSTRAINT fk_message_citations_version_id FOREIGN KEY (version_id)
            REFERENCES document_versions (id) ON DELETE RESTRICT
    )
    """,
    "CREATE INDEX ix_citations_chunk ON message_citations (chunk_id)",
    "CREATE INDEX ix_citations_doc ON message_citations (document_id)",
    """
    CREATE TABLE feedback (
        id         uuid            NOT NULL,
        message_id uuid            NOT NULL,
        user_id    uuid            NULL,
        rating     feedback_rating NOT NULL,
        reason     text            NULL,
        comment    text            NULL,
        created_at timestamptz     NOT NULL DEFAULT now(),
        CONSTRAINT pk_feedback PRIMARY KEY (id),
        CONSTRAINT uq_feedback_message_id_user_id UNIQUE (message_id, user_id),
        CONSTRAINT fk_feedback_message_id FOREIGN KEY (message_id)
            REFERENCES messages (id) ON DELETE CASCADE,
        CONSTRAINT fk_feedback_user_id FOREIGN KEY (user_id)
            REFERENCES users (id) ON DELETE SET NULL
    )
    """,
    """
    CREATE TABLE support_tickets (
        id              uuid            NOT NULL,
        conversation_id uuid            NULL,
        message_id      uuid            NULL,
        requester_name  text            NOT NULL,
        requester_email citext          NOT NULL,
        requester_phone text            NULL,
        subject         text            NOT NULL,
        question        text            NOT NULL,
        transcript      jsonb           NULL,
        priority        ticket_priority NOT NULL DEFAULT 'normal',
        status          ticket_status   NOT NULL DEFAULT 'open',
        assigned_to     uuid            NULL,
        resolution      text            NULL,
        crm_provider    text            NULL,
        crm_ref         text            NULL,
        resolved_at     timestamptz     NULL,
        created_at      timestamptz     NOT NULL DEFAULT now(),
        updated_at      timestamptz     NOT NULL DEFAULT now(),
        CONSTRAINT pk_support_tickets PRIMARY KEY (id),
        CONSTRAINT fk_support_tickets_conversation_id FOREIGN KEY (conversation_id)
            REFERENCES conversations (id) ON DELETE SET NULL,
        CONSTRAINT fk_support_tickets_message_id FOREIGN KEY (message_id)
            REFERENCES messages (id) ON DELETE SET NULL,
        CONSTRAINT fk_support_tickets_assigned_to FOREIGN KEY (assigned_to)
            REFERENCES users (id) ON DELETE SET NULL
    )
    """,
    "CREATE INDEX ix_tickets_status ON support_tickets (status, priority, created_at DESC)",
    """
    CREATE TABLE outbox_events (
        id             uuid        NOT NULL,
        aggregate_type text        NOT NULL,
        aggregate_id   uuid        NOT NULL,
        event_type     text        NOT NULL,
        payload        jsonb       NOT NULL,
        attempts       smallint    NOT NULL DEFAULT 0,
        published_at   timestamptz NULL,
        next_retry_at  timestamptz NULL,
        last_error     text        NULL,
        created_at     timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT pk_outbox_events PRIMARY KEY (id)
    )
    """,
    "CREATE INDEX ix_outbox_pending ON outbox_events (next_retry_at) "
    "WHERE published_at IS NULL",
)

# ── Telemetry (partitioned), prompts, settings, evaluation ──────────────────
# Both telemetry tables are range-partitioned by month. At the modelled volume
# (~50k queries/day) `query_traces` reaches tens of millions of rows in a year; dropping a
# partition is the only retention mechanism that does not spend hours in vacuum.
#
# A DEFAULT partition exists as a safety net so an insert can never fail for want of a
# partition — losing an audit record to a missed maintenance run is not acceptable. The
# maintenance job creates the next month ahead of time, so the default stays empty; if it
# is ever non-empty the job reports it, because rows there block attaching the real
# partition for that range.

TELEMETRY: tuple[str, ...] = (
    """
    CREATE TABLE query_traces (
        id                uuid        NOT NULL,
        created_at        timestamptz NOT NULL DEFAULT now(),
        message_id        uuid        NULL,
        conversation_id   uuid        NULL,
        user_id           uuid        NULL,
        role              user_role   NULL,
        mode              assistant_mode NOT NULL,
        request_id        text        NOT NULL,
        trace_id          text        NULL,
        raw_query         text        NOT NULL,
        intent            text        NULL,
        rewritten_queries jsonb       NOT NULL DEFAULT '[]'::jsonb,
        filter_applied    jsonb       NOT NULL DEFAULT '{}'::jsonb,
        candidates        jsonb       NOT NULL DEFAULT '[]'::jsonb,
        context_chunk_ids uuid[]      NOT NULL DEFAULT '{}'::uuid[],
        context_tokens    integer     NULL,
        stage_latency_ms  jsonb       NOT NULL DEFAULT '{}'::jsonb,
        total_latency_ms  integer     NULL,
        ttft_ms           integer     NULL,
        model             text        NULL,
        provider          text        NULL,
        fallback_used     boolean     NOT NULL DEFAULT false,
        prompt_tokens     integer     NULL,
        completion_tokens integer     NULL,
        cost_usd          numeric(12,6) NULL,
        top_score         double precision NULL,
        mean_top5_score   double precision NULL,
        answer_status     answer_status NULL,
        confidence        double precision NULL,
        guardrail_flags   jsonb       NOT NULL DEFAULT '{}'::jsonb,
        cache_hit         boolean     NOT NULL DEFAULT false,
        error_class       text        NULL,
        error_message     text        NULL,
        CONSTRAINT pk_query_traces PRIMARY KEY (id, created_at)
    ) PARTITION BY RANGE (created_at)
    """,
    "CREATE INDEX ix_traces_created ON query_traces (created_at DESC)",
    "CREATE INDEX ix_traces_status ON query_traces (answer_status, created_at DESC)",
    "CREATE INDEX ix_traces_user ON query_traces (user_id, created_at DESC)",
    "CREATE INDEX ix_traces_message ON query_traces (message_id)",
    "CREATE TABLE query_traces_default PARTITION OF query_traces DEFAULT",
    """
    CREATE TABLE audit_logs (
        id            uuid        NOT NULL,
        created_at    timestamptz NOT NULL DEFAULT now(),
        actor_id      uuid        NULL,
        actor_role    user_role   NULL,
        actor_ip      inet        NULL,
        action        text        NOT NULL,
        resource_type text        NOT NULL,
        resource_id   uuid        NULL,
        outcome       text        NOT NULL DEFAULT 'success',
        before_state  jsonb       NULL,
        after_state   jsonb       NULL,
        request_id    text        NULL,
        user_agent    text        NULL,
        CONSTRAINT pk_audit_logs PRIMARY KEY (id, created_at)
    ) PARTITION BY RANGE (created_at)
    """,
    "CREATE INDEX ix_audit_actor ON audit_logs (actor_id, created_at DESC)",
    "CREATE INDEX ix_audit_resource ON audit_logs (resource_type, resource_id, created_at DESC)",
    "CREATE INDEX ix_audit_action ON audit_logs (action, created_at DESC)",
    "CREATE TABLE audit_logs_default PARTITION OF audit_logs DEFAULT",
    """
    CREATE TABLE prompt_templates (
        id         uuid        NOT NULL,
        key        text        NOT NULL,
        version    integer     NOT NULL,
        mode       assistant_mode NULL,
        body       text        NOT NULL,
        variables  text[]      NOT NULL DEFAULT '{}'::text[],
        is_active  boolean     NOT NULL DEFAULT false,
        notes      text        NULL,
        created_by uuid        NULL,
        created_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT pk_prompt_templates PRIMARY KEY (id),
        CONSTRAINT uq_prompt_templates_key_version UNIQUE (key, version),
        CONSTRAINT fk_prompt_templates_created_by FOREIGN KEY (created_by)
            REFERENCES users (id) ON DELETE SET NULL
    )
    """,
    # One active version per (key, mode) enforced by the database rather than by service
    # code, because "two active system prompts" is a failure nobody notices until answers
    # change for half the traffic.
    "CREATE UNIQUE INDEX ux_prompt_active ON prompt_templates "
    "(key, coalesce(mode::text, 'internal')) WHERE is_active",
    """
    CREATE TABLE settings (
        key        text        NOT NULL,
        value      jsonb       NOT NULL,
        updated_by uuid        NULL,
        updated_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT pk_settings PRIMARY KEY (key),
        CONSTRAINT fk_settings_updated_by FOREIGN KEY (updated_by)
            REFERENCES users (id) ON DELETE SET NULL
    )
    """,
    """
    CREATE TABLE eval_datasets (
        id          uuid        NOT NULL,
        name        text        NOT NULL,
        mode        assistant_mode NOT NULL,
        description text        NULL,
        created_at  timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT pk_eval_datasets PRIMARY KEY (id),
        CONSTRAINT uq_eval_datasets_name UNIQUE (name)
    )
    """,
    """
    CREATE TABLE eval_cases (
        id                    uuid      NOT NULL,
        dataset_id            uuid      NOT NULL,
        question              text      NOT NULL,
        ground_truth          text      NULL,
        expected_document_ids uuid[]    NOT NULL DEFAULT '{}'::uuid[],
        expected_pages        integer[] NOT NULL DEFAULT '{}'::integer[],
        as_role               user_role NOT NULL DEFAULT 'internal_employee',
        must_refuse           boolean   NOT NULL DEFAULT false,
        tags                  text[]    NOT NULL DEFAULT '{}'::text[],
        CONSTRAINT pk_eval_cases PRIMARY KEY (id),
        CONSTRAINT fk_eval_cases_dataset_id FOREIGN KEY (dataset_id)
            REFERENCES eval_datasets (id) ON DELETE CASCADE
    )
    """,
    "CREATE INDEX ix_eval_cases_dataset ON eval_cases (dataset_id)",
    """
    CREATE TABLE eval_runs (
        id              uuid        NOT NULL,
        dataset_id      uuid        NOT NULL,
        git_sha         text        NULL,
        config_snapshot jsonb       NOT NULL DEFAULT '{}'::jsonb,
        status          text        NOT NULL DEFAULT 'running',
        summary         jsonb       NOT NULL DEFAULT '{}'::jsonb,
        started_at      timestamptz NOT NULL DEFAULT now(),
        finished_at     timestamptz NULL,
        triggered_by    uuid        NULL,
        CONSTRAINT pk_eval_runs PRIMARY KEY (id),
        CONSTRAINT fk_eval_runs_dataset_id FOREIGN KEY (dataset_id)
            REFERENCES eval_datasets (id) ON DELETE CASCADE,
        CONSTRAINT fk_eval_runs_triggered_by FOREIGN KEY (triggered_by)
            REFERENCES users (id) ON DELETE SET NULL
    )
    """,
    """
    CREATE TABLE eval_results (
        id                  uuid        NOT NULL,
        run_id              uuid        NOT NULL,
        case_id             uuid        NOT NULL,
        metric              eval_metric NOT NULL,
        score               double precision NOT NULL,
        passed              boolean     NOT NULL,
        answer              text        NULL,
        retrieved_chunk_ids uuid[]      NULL,
        detail              jsonb       NULL,
        CONSTRAINT pk_eval_results PRIMARY KEY (id),
        CONSTRAINT uq_eval_results_run_case_metric UNIQUE (run_id, case_id, metric),
        CONSTRAINT fk_eval_results_run_id FOREIGN KEY (run_id)
            REFERENCES eval_runs (id) ON DELETE CASCADE,
        CONSTRAINT fk_eval_results_case_id FOREIGN KEY (case_id)
            REFERENCES eval_cases (id) ON DELETE CASCADE
    )
    """,
)

# ── Functions and triggers ──────────────────────────────────────────────────
# The denormalized ACL columns (`documents.visibility_level`, `chunks.visibility_level`,
# `chunks.department_path`) exist because the permission filter has to run *inside* the
# vector search, not as a join afterwards. Denormalization without enforcement is how
# permission bugs happen, so the copies are maintained by triggers rather than by
# application code that a future caller can forget.

FUNCTIONS: tuple[str, ...] = (
    """
    CREATE OR REPLACE FUNCTION visibility_to_level(v visibility) RETURNS smallint AS $$
    BEGIN
        RETURN CASE v
            WHEN 'public'       THEN 0
            WHEN 'customer'     THEN 1
            WHEN 'internal'     THEN 2
            WHEN 'confidential' THEN 3
            WHEN 'restricted'   THEN 4
        END;
    END;
    $$ LANGUAGE plpgsql IMMUTABLE
    """,
    """
    CREATE OR REPLACE FUNCTION documents_set_level() RETURNS trigger AS $$
    BEGIN
        NEW.visibility_level := visibility_to_level(NEW.visibility);
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql
    """,
    """
    CREATE TRIGGER trg_documents_set_level
        BEFORE INSERT OR UPDATE OF visibility ON documents
        FOR EACH ROW EXECUTE FUNCTION documents_set_level()
    """,
    # Reclassifying a document has to reach its chunks, or enforcement layer 2 would keep
    # approving chunks whose parent was tightened seconds ago.
    """
    CREATE OR REPLACE FUNCTION documents_propagate_acl() RETURNS trigger AS $$
    BEGIN
        IF NEW.visibility_level IS DISTINCT FROM OLD.visibility_level
           OR NEW.department_path IS DISTINCT FROM OLD.department_path THEN
            UPDATE chunks
               SET visibility_level = NEW.visibility_level,
                   department_path  = NEW.department_path
             WHERE document_id = NEW.id;
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql
    """,
    """
    CREATE TRIGGER trg_documents_propagate_acl
        AFTER UPDATE ON documents
        FOR EACH ROW EXECUTE FUNCTION documents_propagate_acl()
    """,
    # `updated_at` is also maintained by SQLAlchemy's `onupdate`, but a manual SQL fix or a
    # backfill would bypass that; the trigger makes the column trustworthy either way.
    """
    CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger AS $$
    BEGIN
        NEW.updated_at := now();
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql
    """,
    """
    CREATE TRIGGER trg_users_touch BEFORE UPDATE ON users
        FOR EACH ROW EXECUTE FUNCTION touch_updated_at()
    """,
    """
    CREATE TRIGGER trg_documents_touch BEFORE UPDATE ON documents
        FOR EACH ROW EXECUTE FUNCTION touch_updated_at()
    """,
    """
    CREATE TRIGGER trg_collections_touch BEFORE UPDATE ON collections
        FOR EACH ROW EXECUTE FUNCTION touch_updated_at()
    """,
    """
    CREATE TRIGGER trg_tickets_touch BEFORE UPDATE ON support_tickets
        FOR EACH ROW EXECUTE FUNCTION touch_updated_at()
    """,
    # Append-only enforcement for the audit log. In production the application role is also
    # granted only INSERT and SELECT (see infra/postgres/02-grants.sql); this trigger holds
    # even when the application happens to connect as the table owner, which is the case in
    # local development and in most single-role managed setups.
    """
    CREATE OR REPLACE FUNCTION audit_logs_append_only() RETURNS trigger AS $$
    BEGIN
        RAISE EXCEPTION 'audit_logs is append-only (attempted %)', TG_OP;
    END;
    $$ LANGUAGE plpgsql
    """,
    """
    CREATE TRIGGER trg_audit_logs_append_only
        BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH STATEMENT EXECUTE FUNCTION audit_logs_append_only()
    """,
    # Partition maintenance, called by the nightly job and safe to call repeatedly.
    """
    CREATE OR REPLACE FUNCTION ensure_month_partition(base_table text, month_start date)
    RETURNS text AS $$
    DECLARE
        part_name text;
        month_end date;
    BEGIN
        part_name := format('%s_y%sm%s', base_table,
                            to_char(month_start, 'YYYY'), to_char(month_start, 'MM'));
        month_end := (month_start + interval '1 month')::date;
        IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = part_name) THEN
            EXECUTE format(
                'CREATE TABLE %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
                part_name, base_table, month_start, month_end
            );
        END IF;
        RETURN part_name;
    END;
    $$ LANGUAGE plpgsql
    """,
)

# ── Seed data ───────────────────────────────────────────────────────────────
# Permission codes are seeded here because `role_permissions` references them and because
# they are structural, not configuration: they change only when code changes. The
# role→permission matrix itself is seeded by the application from
# `domain.policies.permissions.DEFAULT_ROLE_PERMISSIONS`, so that the matrix an auditor
# reads in version control is the one that runs.

PERMISSION_SEED: tuple[tuple[str, str, str], ...] = (
    ("chat:customer", "chat", "Use the customer support assistant"),
    ("chat:internal", "chat", "Use the internal assistant"),
    ("ticket:create", "support", "Create a support ticket"),
    ("ticket:manage", "support", "Triage and resolve support tickets"),
    ("document:read", "documents", "View document metadata in the admin panel"),
    ("document:write", "documents", "Upload documents and edit metadata"),
    ("document:delete", "documents", "Delete and replace documents"),
    ("document:download", "documents", "Download original files"),
    ("document:reindex", "documents", "Trigger re-chunking or re-embedding"),
    ("acl:manage", "documents", "Edit per-document access grants"),
    ("collection:read", "collections", "View collections"),
    ("collection:manage", "collections", "Create and configure collections"),
    ("user:read", "users", "View users"),
    ("user:manage", "users", "Create, edit, and deactivate users"),
    ("role:manage", "users", "Edit the role permission matrix"),
    ("apikey:manage", "users", "Issue and revoke service API keys"),
    ("analytics:read", "analytics", "View analytics within scope"),
    ("analytics:read_all", "analytics", "View analytics across the organisation"),
    ("audit:read", "audit", "Read audit logs"),
    ("trace:read", "audit", "Read query traces"),
    ("retrieval:debug", "audit", "Run the retrieval debugger"),
    ("prompt:manage", "platform", "Edit and activate prompt templates"),
    ("settings:manage", "platform", "Change runtime settings"),
    ("eval:run", "platform", "Trigger evaluation runs"),
    ("index:manage", "platform", "Rebuild and reconcile the search index"),
)

DROP_ORDER: tuple[str, ...] = (
    "eval_results",
    "eval_runs",
    "eval_cases",
    "eval_datasets",
    "settings",
    "prompt_templates",
    "audit_logs",
    "query_traces",
    "outbox_events",
    "support_tickets",
    "feedback",
    "message_citations",
    "messages",
    "conversations",
    "index_discrepancies",
    "ingest_jobs",
    "chunks",
    "document_acl",
    "document_tags",
    "document_versions",
    "documents",
    "tags",
    "collections",
    "api_keys",
    "refresh_tokens",
    "user_permission_overrides",
    "role_permissions",
    "permissions",
    "users",
    "departments",
)

DROP_TYPES: tuple[str, ...] = (
    "eval_metric",
    "feedback_rating",
    "ticket_status",
    "ticket_priority",
    "principal_type",
    "answer_status",
    "message_role",
    "job_status",
    "ingest_status",
    "chunk_type",
    "assistant_mode",
    "visibility",
    "user_role",
)

DROP_FUNCTIONS: tuple[str, ...] = (
    "DROP FUNCTION IF EXISTS ensure_month_partition(text, date)",
    "DROP FUNCTION IF EXISTS audit_logs_append_only()",
    "DROP FUNCTION IF EXISTS touch_updated_at()",
    "DROP FUNCTION IF EXISTS documents_propagate_acl()",
    "DROP FUNCTION IF EXISTS documents_set_level()",
    "DROP FUNCTION IF EXISTS visibility_to_level(visibility)",
)


def upgrade() -> None:
    for group in (EXTENSIONS, ENUMS, IDENTITY, DOCUMENTS, CONVERSATIONS, TELEMETRY, FUNCTIONS):
        for statement in group:
            op.execute(statement)

    for code, category, description in PERMISSION_SEED:
        op.execute(
            "INSERT INTO permissions (code, category, description) VALUES "
            f"('{code}', '{category}', '{description}')"
        )

    # Partitions for the current and next two months. The nightly maintenance job keeps a
    # rolling window ahead of this; the DEFAULT partitions above cover any gap.
    for base in ("query_traces", "audit_logs"):
        for offset in range(3):
            op.execute(
                "SELECT ensure_month_partition("
                f"'{base}', (date_trunc('month', now()) + interval '{offset} month')::date)"
            )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_append_only ON audit_logs")
    # Per-namespace pgvector tables are created at runtime, so they are dropped by name pattern
    # rather than from a static list. Without this, `chunks` cannot be dropped: the embedding
    # tables hold foreign keys onto it.
    op.execute("""
        DO $$
        DECLARE target text;
        BEGIN
            FOR target IN
                SELECT tablename FROM pg_tables
                WHERE schemaname = current_schema() AND tablename LIKE 'emb\\_%'
            LOOP
                EXECUTE format('DROP TABLE IF EXISTS %I CASCADE', target);
            END LOOP;
        END $$
    """)
    for table in DROP_ORDER:
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
    for statement in DROP_FUNCTIONS:
        op.execute(statement)
    for type_name in DROP_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
